.TH foobar "42" "Testing File"

.SH NAME foobar \- Sample man page

.SH SYNOPSIS
.B foobar [baz] -q -u -x

.SH DESCRIPTION
This is just a sample based on the example provided
by http://www.tldp.org/HOWTO/Man-Page/q3.html

.SH OPTIONS
.IP -q
q is an option

.IP -u
u is an option

.IP -x
x is an option

.SH BUGS
This is flawless
